### ISSUE TITLE
Add an option to json_lines codec to ignore blank lines

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-codec-json_lines#5]
(This issue was originally filed by @dimas at https://github.com/elastic/logstash/issues/2621)

---

When connection to logstash is established through some kind of proxy like Amazon ELB, you need to keep that connection alive byt sending something from time to time or load balancer will kill it.

For json_lines codec the most logical choice for that "keepalive" payload is a single newline character without any JSON. Unfortunately, the way json_lines if written, it will result in an event to be generated.

It would be nice to have an option for json_lines to tell it to ignore blank lines (or just ignore blank lines by default). 
(It is much more tricky to filter out these messages on a later stages because as lots of fields is added by logstash itself, the only reliable of a keepalive message is "message" set to "". But if you think of it, that indicator is not reliable at all because it is perfectly valid for a "message" to be blank and carry all the information in other fields)

**Comment by dimas** [comment]
There is already a pull request I created to fix it - https://github.com/logstash-plugins/logstash-codec-json_lines/pull/2 but apparently it is not valid anymore because of a merge conflic...

The change is very simple though so I would really prefer if you fixed that conflict yourself if you do not mind accepting it at all. This is because given the round trip time in or conversation, by the moment you will read this, there will be another merge conflict even if I fix it right now :)

Thanks

**Comment by colinsurprenant** [comment]
is there a good reason to make that configurable? since we are talking about decoding json, empty lines should just be systematically ignored IMO. 
we've had another issue reported which relates to this: elastic/logstash/issues/4618

Thanks @dimas for your contribution & patience on this. As you suggested I think it will just be faster for me to submit a new PR than to deal with merge conflicts.

**Comment by colinsurprenant** [comment]
this will be solved by #22 and elastic/logstash/pull/4671
